# CLUSTERS

# Refers to Kubernetes cluster where ArgoCD can deploy applications.
# By Default, ArgoCD interacts with the Kubernetes cluster where it's installed.
# The credentials for external clusters are stored in Kubernetes Secret, allowing ArgoCD to securely authenticate and deploy resources.

apiVersion: v1
kind: Secret  # The cluster's access credentials are stored in a Kubernetes Secret
metadata:
  name: prod-cluster-secret  # Name of the secret (used by ArgoCD to reference the cluster)
  namespace: argocd  # Namespace where ArgoCD is installed
  labels:
    argocd.argoproj.io/secret-type: cluster  # Label indicating that this secret contains cluster credentials
data:
  name: prod-cluster  # Base64-encoded name of the cluster (human-readable name used in the UI)
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmV4YW1wbGUuY29t  # Base64-encoded URL of the Kubernetes API server
  config:  # Base64-encoded kubeconfig-style configuration, including authentication and TLS details
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: # Base64-encoded CA certificate data
        server: https://kubernetes.example.com  # The cluster's API server URL
      name: prod-cluster
    contexts:
    - context:
        cluster: prod-cluster
        user: prod-cluster-admin  # User for authentication
      name: prod-cluster-context
    current-context: prod-cluster-context
    kind: Config
    preferences: {}
    users:
    - name: prod-cluster-admin  # Authentication user
      user:
        token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJbXRwWkNJNkltRmpZWFJoWjJWbFpHVmliR2xtYVhSbGN5STZJbEJ5YjJodmIzTmxMbUpwYkdsemRXVnlhV1FpT2lKb1pTSTZJaklpZlE=
        # The authentication token (Base64-encoded)

---

# metadata.name: The name of the secret used to identify the cluster in ArgoCD.
# metadata.namespace: The namespace where ArgoCD is installed (usually argocd).
# metadata.labels: The label argocd.argoproj.io/secret-type: cluster specifies that this secret contains cluster credentials.
# data.name: The base64-encoded name of the cluster, shown in the ArgoCD UI.
# This is a human-readable name that helps differentiate clusters in the UI (e.g., prod-cluster or dev-cluster).
# data.server: The base64-encoded URL of the Kubernetes API server for the cluster.
# This is where ArgoCD will send requests to deploy applications, perform syncs, and query the cluster for the status of resources.
# data.config: Contains the cluster configuration and authentication details in the format of a kubeconfig file.
# clusters.cluster.certificate-authority-data: The base64-encoded CA certificate for the cluster. This is used to verify the authenticity of the cluster’s API server.
# clusters.cluster.server: The API server URL of the Kubernetes cluster.
# contexts.context.user: Specifies the user that will authenticate when ArgoCD interacts with this cluster.
# users.user.token: The base64-encoded authentication token for accessing the Kubernetes API. This can be a service account token or any other method of authentication supported by Kubernetes.
