
# **SecretGenerator:** Dynamically generates Kubernetes Secrets from literals, files, or environment variables, and automatically appends a hash for versioning.

# Each generator accepts **behavior** parameter:
# - create (default): creates new ConfigMap/Secret
# - replace: replace existing ConfigMap/Secret from the base
# - merge: add/opdate values in existing ConfigMap/Secret from the base

## Generating Secrets
# Generate Secrets dynamically based on literal values, files or environmental variabls
# - **literals:** Provides key-value pairs as string literals.
# - **files:** Specifies file paths whose content will be encoded and added as data to the Secret.
# - **envs:** Points to a file containing environment variables (in the form KEY=VALUE) loaded into the Secret

# **kustomization.yaml**
secretGenerator:
  - name: db-credentials
    literals:
      - username=admin
      - password=securepass123
    files:
      - ssh-key=/path/to/ssh-keyfile

# This will generate a Secret named db-credentials with username, password, and the content of ssh-key as part of the Secret.
