apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: my-secret
    type: kubernetes.io/tls
    data:
    - objectName: my-secret
      key: tls.key
  parameters:
    usePodIdentity: "false"
    keyvaultName: '>>KEY-VAULT-NAME<<'
    tenantID: '>>TENANT-ID<<'
    clientID: '>>CLIENT-ID-MSI<<'
    objects:  |
      array:
        - objectName: my-secret
          objectType: secret
