apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-redis
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      name: redis
  selector:
    app: {{ include "fullname" . }}-redis
  type: ClusterIP
