apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-postgres-auth
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.auth.password }}
  POSTGRES_DB: {{ .Values.auth.database }}
