
# route traffic based on request headers (A/B testing)

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
    - my-service
  http:
    - match:
        - headers:
            user-agent:
              regex: .*Mobile.*
      route:
        - destination:
            host: my-service
            subset: mobile
    - route:
        - destination:
            host: my-service
            subset: desktop

---
