
# Library Charts unline regular Helm Charts don't include deployment specifics
# used to share common templates, promoting code reuse and consistency across charts

$ helm create myapp
$ rm -rf myapp/template/* # delete all generated templates bcz we will use from lib chart
$ vim myapp/Chart.yml # add dependency

---

apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

---

appVersion: "1.16.0"
# Add the Bitnami library chart as dependency
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x