- name: Install Nginx on Web Servers
  hosts: webservers # specifies target host group
  become: true      # uses sudo for privilege escalation
  tasks:            # list of actions to execute
    - name: Install Nginx # describes the play
      apt:
        name: nginx
        state: present

## variables & facts
- name: Deploy Application
  hosts: webservers
  vars: # variable
    app_port: 8080
  tasks:
    - name: Create configuration file
      template:
        src: config.j2
        dest: /etc/app/config.cfg

- name: Display system facts  # ansible gathers system information (ansible_facts) automatically
  hosts: all
  tasks:
    - name: Print OS and IP
      debug:
        msg: "System {{ ansible_distribution }} has IP {{ ansible_default_ipv4.address }}" # ansible_distribution is an example of ansible

## conditionals & loops
